#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "health.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/start.h"
#include "images/win.h"
#include "images/lose.h"
#include "images/gojo.h"
#include "images/sukuna.h"
#include "images/HollowR.h"
#include "images/HollowB.h"
#include "images/HollowP.h"
#include "images/slash.h"
/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  SELECTBLUE,
  SELECTRED,
  SELECTPURPLE,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //

  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  struct player player = {80, 20, 20, 30};
  int speed = 2;
  int jumpSpeed = 5;
  int jumpHeight = 40;
  int jumpCount = 0;
  int isJumping = 0;
  int HollowBlue = 0;
  int HollowRed = 0;
  int HollowPurple = 0;

  int timer = 1500;
  int count = 0;
  int playCount = 0;
  int texty = 100;
  int texty2 = 100;
  int textSpeed = 1;
  int textSpeed2 = 1.5;

  struct enemy goat = {100, WIDTH - 40, 20, 40};

  struct HollowRed red = {-5, -5, 3, 0};
  struct HollowBlue blue = {-5, -5, 3, 0};
  struct HollowPurple purple = {-35, -35, 10, 0};
  struct HollowPurple cleave = {-35, -35, 15, 0};

  struct platform platform1 = {140, 0, 240, 40};

  struct healthBar health;
  initializeHealth(&health, 5, 5, 100, 10, 100, RED);

  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (state) {
      case START:
      if (count == 0) {
        waitForVBlank();
        drawFullScreenImageDMA(start);
        count = 1;
      }

      if (texty >= 210) {
         textSpeed = -1;
       } else if (texty <= 0){
         textSpeed = 1;
      }
      if (texty2 >= 220) {
         textSpeed2 = -1.5;
       } else if (texty2 <= 0){
         textSpeed2 = 1.5;
      }
        texty += textSpeed;
        texty2 += textSpeed2;

        drawString(120, texty, "ENTER", BLACK);
        drawString(130, texty2, "NOW", BLACK);
  
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = SELECTBLUE;
          drawFullScreenImageDMA(HollowB);
          vBlankCounter = 0;
          break;
        }

        player.charX = 80;
        player.charY = 20;
        player.charW = 20;
        player.charH = 30;
        speed = 2;
        jumpSpeed = 5;
        jumpHeight = 40;
        jumpCount = 0;
        isJumping = 0;

        timer = 1500;
        count = 0;

        playCount = 0;
        initializeHealth(&health, 5, 135, 100, 10, 100, RED);

        goat.enemyX = 100;
        goat.enemyY = WIDTH - 40;
        goat.enemyW = 20;
        goat.enemyH = 40;

        if (HollowRed == 1) {
          red.redR = -5;
          red.redC = -5;
          red.redSize = 3;
          red.redVel = 0;
        }
        
        if (HollowBlue == 1) {
          blue.blueR = -5;
          blue.blueC = -5;
          blue.blueSize = 3;
          blue.blueVel = 0;
        }

        if (HollowPurple == 1) {
          purple.purpleR = -35;
          purple.purpleC = -35;
          purple.purpleSize = 10;
          purple.purpleVel = 0;
        }

        cleave.purpleR = -35;
        cleave.purpleC = -35;
        cleave.purpleSize = 15;
        cleave.purpleVel = -2;

        platform1.x = 140;
        platform1.y = 0;
        platform1.width = 240;
        platform1.height = 40;
        // state = ?

        break;

      case SELECTBLUE:
      waitForVBlank();
      currentButtons = BUTTONS;
      drawString(100, 80, "Select An Attack", YELLOW);
      waitForVBlank();
      drawString(130, 50, "RED", BLACK);
      waitForVBlank();
      drawString(130, 110, "BLUE", YELLOW);
      waitForVBlank();
      drawString(130, 170, "PURPLE", BLACK);
      waitForVBlank();
      waitForVBlank();

      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        texty = 100;
        texty2 = 100;
        textSpeed = 1;
        textSpeed2 = 1.5;
        break;
      }

      for (u32 i = 0; i < 500 * 1000; i++) {
              currentButtons = BUTTONS;
              if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
                state = START;
                texty = 100;
                texty2 = 100;
                textSpeed = 1;
                textSpeed2 = 1.5;
                break;
            }
              if (KEY_DOWN(BUTTON_A, BUTTONS)) {
                state = PLAY;
                HollowBlue = 1;
                HollowPurple = 0;
                HollowRed = 0;
                fillScreenDMA(GRAY);
                waitForVBlank();
                break;
            } 
            if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
                state = SELECTPURPLE;
                drawFullScreenImageDMA(HollowP);
                waitForVBlank();
                break;
            }
            if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
                state = SELECTRED;
                drawFullScreenImageDMA(HollowR);
                waitForVBlank();
                break;
            }
        }
        waitForVBlank();

      break;
      case SELECTRED:
      waitForVBlank();  
      currentButtons = BUTTONS;
      drawString(100, 80, "Select An Attack", YELLOW);
      waitForVBlank();
      drawString(130, 50, "RED", YELLOW);
      waitForVBlank();
      drawString(130, 110, "BLUE", BLACK);
      waitForVBlank();
      drawString(130, 170, "PURPLE", BLACK);
      waitForVBlank();
      waitForVBlank();

      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        texty = 100;
        texty2 = 100;
        textSpeed = 1;
        textSpeed2 = 1.5;
        break;
      }

      for (u32 i = 0; i < 500 * 1000; i++) {
              currentButtons = BUTTONS;
              if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            texty = 100;
            texty2 = 100;
            textSpeed = 1;
            textSpeed2 = 1.5;
            break;
            }
              if (KEY_DOWN(BUTTON_A, BUTTONS)) {
                state = PLAY;
                HollowBlue = 0;
                HollowPurple = 0;
                HollowRed = 1;
                fillScreenDMA(GRAY);
                waitForVBlank();
                break;
            } 
            if (KEY_JUST_PRESSED(BUTTON_RIGHT, BUTTONS, previousButtons)) {
                state = SELECTBLUE;
                drawFullScreenImageDMA(HollowB);
                waitForVBlank();
                break;
            }
        }
        waitForVBlank();
      break;
      case SELECTPURPLE:
        waitForVBlank();  
      currentButtons = BUTTONS;
      drawString(100, 80, "Select An Attack", YELLOW);
      waitForVBlank();
      drawString(130, 50, "RED", BLACK);
      waitForVBlank();
      drawString(130, 110, "BLUE", BLACK);
      waitForVBlank();
      drawString(130, 170, "PURPLE", YELLOW);
      waitForVBlank();
      waitForVBlank();

      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        texty = 100;
        texty2 = 100;
        textSpeed = 1;
        textSpeed2 = 1.5;
        break;
      }

      for (u32 i = 0; i < 500 * 1000; i++) {
              currentButtons = BUTTONS;
              if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
            state = START;
            texty = 100;
            texty2 = 100;
            textSpeed = 1;
            textSpeed2 = 1.5;
            break;
            }
              if (KEY_DOWN(BUTTON_A, BUTTONS)) {
                state = PLAY;
                HollowBlue = 0;
                HollowPurple = 1;
                HollowRed = 0;
                fillScreenDMA(GRAY);
                waitForVBlank();
                break;
            } 
            if (KEY_JUST_PRESSED(BUTTON_LEFT, BUTTONS, previousButtons)) {
                state = SELECTBLUE;
                drawFullScreenImageDMA(HollowB);
                waitForVBlank();
                break;
            }
        }
        waitForVBlank();
      break;
      case PLAY:
      
          timer--;
          if (timer <= 0) {
            state = LOSE;
            break;
          }
          drawRectDMA(player.charX, player.charY, player.charW, player.charH, GRAY);
          drawRectDMA(red.redR, red.redC, red.redSize, red.redSize, GRAY);
          drawRectDMA(blue.blueR, blue.blueC, blue.blueSize, blue.blueSize, GRAY);
          drawRectDMA(purple.purpleR, purple.purpleC, purple.purpleSize, purple.purpleSize, GRAY);
          drawRectDMA(cleave.purpleR, cleave.purpleC, cleave.purpleSize, cleave.purpleSize, GRAY);
          drawRectDMA(150, 40, 30, 30, BLACK);

          if (playCount == 0) {
            drawRectDMA(platform1.x, platform1.y, platform1.width, platform1.height, BLACK);
            drawString(150, 100, "BEAT SUKUNA", WHITE);
            playCount = 1;
          }
          ///ERASING^

          if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            state = START;
            texty = 100;
            texty2 = 100;
            textSpeed = 1;
            textSpeed2 = 1.5;
            break;
          }

          if (health.curr == 0) {
            state = WIN;
            break;
          }

          if (HollowRed == 1) {
            if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
              red.redR = player.charX + 12;
              red.redC = player.charY + 20;
              red.redVel = 2;
            }
            if (red.redC == goat.enemyY && red.redR >= goat.enemyX) {
              red.redVel = 0;
              red.redC = -5;
              red.redR = -5;
              updateHealth(&health, 2);
            } else if (red.redC >= 235 || red.redC <= 0) {
              red.redVel = 0;
              red.redC = -5;
              red.redR = -5;
            } else {
              red.redC += red.redVel;
            }
          }

          if (HollowBlue == 1) {
            if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
              blue.blueR = player.charX + 12;
              blue.blueC = player.charY + 20;
              blue.blueVel = 2;
            }
            if (blue.blueC == goat.enemyY && blue.blueR >= goat.enemyX) {
              blue.blueVel = 0;
              blue.blueC = -5;
              blue.blueR = -5;
              updateHealth(&health, 2);
            } else if (blue.blueC >= 235 || blue.blueC <= 0) {
              blue.blueVel = 0;
              blue.blueC = -5;
              blue.blueR = -5;
            } else {
              blue.blueC += blue.blueVel;
            }
          }

          if (HollowPurple == 1) {
            if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
              purple.purpleR = player.charX + 12;
              purple.purpleC = player.charY + 20;
              purple.purpleVel = 2;
            }
            if (purple.purpleC >= goat.enemyY - 10 && purple.purpleR >= goat.enemyX) {
              purple.purpleVel = 0;
              purple.purpleC = -35;
              purple.purpleR = -35;
              updateHealth(&health, 5);
            } else if (purple.purpleC >= 230 || purple.purpleC <= -5) {
              purple.purpleVel = 0;
              purple.purpleC = -35;
              purple.purpleR = -35;
            } else {
              purple.purpleC += purple.purpleVel;
            }
          }

          if (timer/60 % 5 == 0) {
            cleave.purpleR = goat.enemyX + 20;
            cleave.purpleC = goat.enemyY - 12;
            cleave.purpleVel = -2;
          }

          if ((cleave.purpleC == player.charY + 20) && (cleave.purpleR >= player.charX) && (cleave.purpleR <= player.charX + player.charH)) {
              cleave.purpleVel = 0;
              cleave.purpleC = -35;
              cleave.purpleR = -35;
              state = LOSE;
              break;
            } else if (cleave.purpleC <= 0 || cleave.purpleC >= 235) {
              cleave.purpleVel = 0;
              cleave.purpleC = -35;
              cleave.purpleR = -35;
            } else {
              cleave.purpleC += cleave.purpleVel;
            }

          if (KEY_DOWN(BUTTON_UP, currentButtons)) {
            if (player.charX - 1 < 0) {
              player.charX = 0;
            } else {
              player.charX -= 1;
            }
          }
          if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
            if (player.charX + player.charH + 1 > platform1.y) {
              player.charX = player.charX;
            } else {
                player.charX += 1;
            }
          }
          if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
            if (player.charY - 1 < 0) {
              player.charY = 0;
            } else {
              player.charY -= speed;
            }
          }
          if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
            if (player.charY + player.charW + 1 > goat.enemyY) {
              state = LOSE;
              break;
            } else {
              player.charY += speed;
            }
          }
          if (isJumping == 1) {
            player.charX -= jumpSpeed;
            jumpCount += jumpSpeed;
            if (jumpCount >= jumpHeight) {
              isJumping = 0;
              jumpCount = 0;
            } 
          } else {
              player.charX += 10;
              if (player.charX + player.charH >= 140) {
                player.charX = 140 - player.charH;
              }
            }

            if (KEY_DOWN(BUTTON_B, currentButtons) && !KEY_DOWN(BUTTON_B, previousButtons)) {
              if (isJumping == 0) {
                isJumping = 1;
              }
            }

          
          ///MOVEMENT^

          drawImageDMA(player.charX, player.charY, player.charW, player.charH, gojo);
          drawImageDMA(goat.enemyX, goat.enemyY, goat.enemyW, goat.enemyH, sukuna);
          drawRectDMA(red.redR, red.redC, red.redSize, red.redSize, RED);
          drawRectDMA(blue.blueR, blue.blueC, blue.blueSize, blue.blueSize, BLUE);
          drawRectDMA(purple.purpleR, purple.purpleC, purple.purpleSize, purple.purpleSize, MAGENTA);
          drawImageDMA(cleave.purpleR, cleave.purpleC, cleave.purpleSize, cleave.purpleSize, slash);
          char TimeStr[20];
          drawHealth(&health);
          snprintf(TimeStr, 20, "Time: %d", timer/60);
          drawString(150, 10, TimeStr, WHITE);
        ///REDRAWING^
        
        // state = ?
        break;
      case WIN:
      drawFullScreenImageDMA(win);
      drawString(130, 20, "MAHORAGA", BLACK);
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        texty = 100;
        texty2 = 100;
        textSpeed = 1;
        textSpeed2 = 1.5;
        break;
      }
        // state = ?
        break;
      case LOSE:
      drawFullScreenImageDMA(lose);
      drawString(150, 90, "STAND PROUD", BLACK);
      if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
        state = START;
        texty = 100;
        texty2 = 100;
        textSpeed = 1;
        textSpeed2 = 1.5;
        break;
      }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
